In [1]:
import pandas as pd 
print("Python works!")

Python works!

In [3]:
import sqlite3
import pandas as pd 

conn = sqlite3.connect("/Users/zeynep/Desktop/python-sql-practice/database/practice.db")

query = "SELECT * FROM employees" 

df = pd.read_sql(query, conn)

df

Empty DataFrame
Columns: [id, name, salary, department]
Index: []

In [4]:
import sqlite3
import pandas as pd 

conn = sqlite3.connect("/Users/zeynep/Desktop/python-sql-practice/database/practice.db")

query = "SELECT * FROM employees" 

tables = pd.read_sql(query, conn)

tables

Empty DataFrame
Columns: [id, name, salary, department]
Index: []

In [13]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("/Users/zeynep/Desktop/python-sql-practice/database/practice.d")
cursor = conn.cursor()

cursor.execute(""" 
CREATE TABLE IF NOT EXISTS employees (
    id INTEGER PRIMARY KEY,
    name TEXT,
    salary INTEGER,
    department TEXT
)
""")

cursor.execute("INSERT INTO employees (name, salary, department) VALUES ('Ali', 50000, 'IT')")
cursor.execute("INSERT INTO employees (name, salary, department) VALUES ('Ayşe', 65000, 'HR')")
cursor.execute("INSERT INTO employees (name, salary, department) VALUES ('Mehmet', 72000, 'Finance')")

conn.commit()

query = "SELECT * FROM employees"
df = pd.read_sql(query, conn)
df

   id    name  salary department
0   1     Ali   50000         IT
1   2    Ayşe   65000         HR
2   3  Mehmet   72000    Finance

In [6]:
cursor.execute("""
    DELETE FROM employees
    WHERE id NOT IN (
        SELECT MIN(id) FROM employees
        GROUP BY name, salary, department
    )
""")
conn.commit()

In [7]:
query = "SELECT * FROM employees"
df = pd.read_sql(query, conn)
df

   id    name  salary department
0   1     Ali   50000         IT
1   2    Ayşe   65000         HR
2   3  Mehmet   72000    Finance

In [8]:
import os

db_path = "/Users/zeynep/Desktop/python-sql-practice/database/practice.db"
print(os.path.abspath(db_path))

/Users/zeynep/Desktop/python-sql-practice/database/practice.db

In [9]:
import sqlite3

db_path = "/Users/zeynep/Desktop/python-sql-practice/database/practice.db"
conn = sqlite3.connect(db_path)
cursor = conn.cursor()

print("Bağlanılan db:", db_path)

Bağlanılan db: /Users/zeynep/Desktop/python-sql-practice/database/practice.db

In [16]:
import pandas as pd

df = pd.read_sql("SELECT * FROM employees", conn)
print(df)

   id    name  salary department
0   1     Ali   50000         IT
1   2    Ayşe   65000         HR
2   3  Mehmet   72000    Finance

In [17]:
count_df = pd.read_sql("SELECT COUNT(*) as total FROM employees", conn)
print(count_df)

   total
0      3

In [18]:
df = pd.read_sql("SELECT id, name, salary, department FROM employees ORDER BY id", conn)
print(df)

   id    name  salary department
0   1     Ali   50000         IT
1   2    Ayşe   65000         HR
2   3  Mehmet   72000    Finance

In [11]:
cursor.execute("""
INSERT INTO employees (name, salary, department)
VALUES ('Deneme', 1234, 'Test')
""")
conn.commit()

In [14]:
import pandas as pd

df = pd.read_sql("SELECT * FROM employees", conn)
print(df)

   id    name  salary department
0   1     Ali   50000         IT
1   2    Ayşe   65000         HR
2   3  Mehmet   72000    Finance

In [19]:
import sqlite3
import pandas as pd
import os

db_path = "/Users/zeynep/Desktop/python-sql-practice/database/practice.db"
print("DB yolu:", os.path.abspath(db_path))

conn = sqlite3.connect(db_path)
cursor = conn.cursor()

tables = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", conn)
print("Tablolar:")
print(tables)

df = pd.read_sql("SELECT id, name, salary, department FROM employees ORDER BY id;", conn)
print("Employees tablosu:")
print(df)

conn.close()

DB yolu: /Users/zeynep/Desktop/python-sql-practice/database/practice.db
Tablolar:
        name
0  employees
Employees tablosu:
     id    name  salary department
0  None  Deneme    1234       Test

In [20]:
import sqlite3
import pandas as pd

db_path = "/Users/zeynep/Desktop/python-sql-practice/database/practice.db"
conn = sqlite3.connect(db_path)
cursor = conn.cursor()

cursor.execute("DROP TABLE IF EXISTS employees")

cursor.execute("""
CREATE TABLE employees (
    id INTEGER PRIMARY KEY,
    name TEXT,
    salary INTEGER,
    department TEXT
)
""")

cursor.execute("INSERT INTO employees (name, salary, department) VALUES ('Ali', 5000, 'IT')")
cursor.execute("INSERT INTO employees (name, salary, department) VALUES ('Ayşe', 6500, 'HR')")
cursor.execute("INSERT INTO employees (name, salary, department) VALUES ('Mehmet', 7200, 'Finance')")

conn.commit()

df = pd.read_sql("SELECT * FROM employees", conn)
print(df)

conn.close()

   id    name  salary department
0   1     Ali    5000         IT
1   2    Ayşe    6500         HR
2   3  Mehmet    7200    Finance

In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("../database/nyc.db")

print(pd.read_sql("SELECT COUNT(*) AS total_rows FROM airbnb_listings;", conn))
print(pd.read_sql("SELECT * FROM airbnb_listings LIMIT 5;", conn))

conn.close()

   total_rows
0       12720
     id                                name  host_id    host_name  \
0  2539  Clean & quiet apt home by the park     2787         John
1  2595               Skylit Midtown Castle     2845     Jennifer
2  3831     Cozy Entire Floor of Brownstone     4869  LisaRoxanne
3  5238  Cute & Cozy Lower East Side 1 bdrm     7549          Ben
4  7322                     Chelsea Perfect    18946         Doti

  neighbourhood_group neighbourhood  latitude  longitude        room_type  \
0            Brooklyn    Kensington  40.64749  -73.97237     Private room
1           Manhattan       Midtown  40.75362  -73.98377  Entire home/apt
2            Brooklyn  Clinton Hill  40.68514  -73.95976  Entire home/apt
3           Manhattan     Chinatown  40.71344  -73.99037  Entire home/apt
4           Manhattan       Chelsea  40.74192  -73.99501     Private room

   price  minimum_nights  number_of_reviews last_review  reviews_per_month  \
0    149               1                  9  2018-10-19               0.21
1    225               1                 45  2019-05-21               0.38
2     89               1                270  2019-07-05               4.64
3    150               1                160  2019-06-09               1.33
4    140               1                260  2019-07-01               2.12

   calculated_host_listings_count  availability_365 price_category  is_active  \
0                               6               365         Medium          1
1                               2               355      Expensive          1
2                               1               194          Cheap          1
3                               4               188         Medium          1
4                               1                12         Medium          1

   price_per_review
0         14.900000
1          4.891304
2          0.328413
3          0.931677
4          0.536398